version: '3.4'

services:

  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "Your_password123"
       ACCEPT_EULA: "Y"